# Generated by Django 4.0.3 on 2022-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
        migrations.AddField(
            model_name='user',
            name='buissness_logo',
            field=models.ImageField(default='hello', upload_to='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='buissness_name',
            field=models.CharField(default=122, max_length=100),
            preserve_default=False,
        ),
    ]
