# Generated by Django 4.0.3 on 2022-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_pic_user_buissness_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
